/**
 * Audits Shopify Liquid filter/tag compatibility.
 *
 * For each Shopify filter and tag, reports whether it's:
 * - ✅ Fully supported (LiquidJS core)
 * - ☑️ Functionally supported (Assay shim)
 * - Unsupported (blank)
 *
 * Outputs docs/filters.md and docs/tags.md.
 */

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Liquid } from "liquidjs";
import type { ShimFilter, ShimTag } from "../src/shims";
import {
	filters as assayFilterShims,
	tags as assayTagShims,
} from "../src/shims";

type Status = "core" | "assay" | "missing";

interface AuditedEntry {
	name: string;
	status: Status;
	description: string;
}

interface AuditResult {
	rows: string[];
	deprecatedRows: string[];
	counts: Record<Status, number>;
	total: number;
}

interface ShopifyEntry {
	name: string;
	summary: string;
	deprecated: boolean;
}

const projectRoot = resolve(import.meta.dirname, "..");
const docsDataPath = resolve(projectRoot, "vendor/theme-liquid-docs/data");

function readShopifyData(filename: string): ShopifyEntry[] {
	return JSON.parse(readFileSync(resolve(docsDataPath, filename), "utf-8"));
}

function audit(
	shopifyEntries: ShopifyEntry[],
	coreNames: Set<string>,
	shimMap: Map<string, ShimFilter | ShimTag>,
): AuditResult {
	const shimNames = new Set(shimMap.keys());
	const active: AuditedEntry[] = [];
	const deprecated: AuditedEntry[] = [];

	for (const entry of shopifyEntries) {
		const audited = auditEntry(entry, coreNames, shimNames, shimMap);
		if (entry.deprecated) {
			deprecated.push(audited);
		} else {
			active.push(audited);
		}
	}

	// Add Assay shims not in the Shopify list
	const knownNames = new Set(shopifyEntries.map((entry) => entry.name));
	for (const [name, shim] of shimMap) {
		if (!knownNames.has(name)) {
			active.push({
				name,
				status: "assay",
				description: shim.description ?? "",
			});
		}
	}

	active.sort((first, second) => first.name.localeCompare(second.name));
	deprecated.sort((first, second) => first.name.localeCompare(second.name));

	const counts: Record<Status, number> = { core: 0, assay: 0, missing: 0 };
	for (const entry of active) {
		counts[entry.status]++;
	}

	return {
		rows: active.map(formatRow),
		deprecatedRows: deprecated.map(formatRow),
		counts,
		total: active.length,
	};
}

function auditEntry(
	entry: ShopifyEntry,
	coreNames: Set<string>,
	shimNames: Set<string>,
	shimMap: Map<string, ShimFilter | ShimTag>,
): AuditedEntry {
	const status = coreNames.has(entry.name)
		? "core"
		: shimNames.has(entry.name)
			? "assay"
			: "missing";

	const shim = shimMap.get(entry.name);
	const description = resolveDescription(entry, shim);

	return { name: entry.name, status, description };
}

function resolveDescription(
	entry: ShopifyEntry,
	shim: ShimFilter | ShimTag | undefined,
): string {
	if (shim?.description && entry.summary) {
		console.warn(
			`⚠️  Both shim and Shopify define description for: ${entry.name}`,
		);
	}
	if (shim?.description) return shim.description;
	if (entry.summary) return entry.summary;
	console.warn(`⚠️  No description for: ${entry.name}`);
	return "";
}

const statusDisplay: Record<Status, { icon: string; label: string }> = {
	core: { icon: "✅", label: "LiquidJS" },
	assay: { icon: "☑️", label: "Assay" },
	missing: { icon: "", label: "" },
};

function formatRow(entry: AuditedEntry): string {
	const { icon, label } = statusDisplay[entry.status];
	const description = entry.description
		.replace(/\|/g, "\\|")
		.replace(/\n/g, " ");
	return `| \`${entry.name}\` | ${icon} | ${label} | ${description} |`;
}

function buildMarkdown(title: string, result: AuditResult): string {
	const header = [
		"<!--Auto-generated by `npm run docs:audit`. Do not edit manually.-->",
		"",
		`# ${title}`,
		"",
		`- ✅ Parity: ${result.counts.core}`,
		`- ☑️ Mock: ${result.counts.assay}`,
		`- Unsupported: ${result.counts.missing}`,
		`- **Total:** ${result.total}`,
		"",
		`| ${title.slice(0, -1)} | | By | Description |`,
		`| ${"-".repeat(title.length - 1)} | - | -- | ----------- |`,
		...result.rows,
	];

	if (result.deprecatedRows.length > 0) {
		header.push(
			"",
			"## Deprecated",
			"",
			`| ${title.slice(0, -1)} | | By | Description |`,
			`| ${"-".repeat(title.length - 1)} | - | -- | ----------- |`,
			...result.deprecatedRows,
		);
	}

	header.push("");
	return header.join("\n");
}

// --- Main ---

const engine = new Liquid();
const coreFilterNames = new Set(Object.keys(engine.filters));
const coreTagNames = new Set(Object.keys(engine.tags));

const filterShimMap = new Map(
	assayFilterShims.map((filter) => [filter.name, filter]),
);
const tagShimMap = new Map(assayTagShims.map((tag) => [tag.name, tag]));

const filterResult = audit(
	readShopifyData("filters.json"),
	coreFilterNames,
	filterShimMap,
);
const tagResult = audit(readShopifyData("tags.json"), coreTagNames, tagShimMap);

writeFileSync(
	resolve(projectRoot, "docs/filters.md"),
	buildMarkdown("Filters", filterResult),
);
writeFileSync(
	resolve(projectRoot, "docs/tags.md"),
	buildMarkdown("Tags", tagResult),
);

console.log(
	`Filters: ${filterResult.counts.core} core, ${filterResult.counts.assay} assay, ${filterResult.counts.missing} unsupported`,
);
console.log(
	`Tags: ${tagResult.counts.core} core, ${tagResult.counts.assay} assay, ${tagResult.counts.missing} unsupported`,
);

execSync("npm run lint:fix", { cwd: projectRoot, stdio: "inherit" });
