/**
 * Audits Shopify Liquid filter/tag compatibility.
 *
 * For each Shopify filter and tag, reports whether it's:
 * - ✅ Fully supported (LiquidJS core or Assay parity shim)
 * - ☑️ Functionally supported (Assay mock shim)
 * - Unsupported (blank)
 *
 * Outputs docs/filters.md and docs/tags.md.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Liquid } from "liquidjs";
import type { ShimFilter, ShimStatus, ShimTag } from "../src/shims";
import {
	filters as assayFilterShims,
	tags as assayTagShims,
} from "../src/shims";
import { formatTable } from "./utilities/markdown-table";
import { getStatusWithLabel } from "./utilities/status";

type Status = "core" | "assay" | "missing";

interface AuditedEntry {
	name: string;
	kind: "filter" | "tag";
	status: Status;
	shimStatus?: ShimStatus;
	description: string;
	hasShopifyDocs: boolean;
}

interface AuditResult {
	active: AuditedEntry[];
	deprecated: AuditedEntry[];
	counts: { parity: number; mock: number; unsupported: number };
}

interface ShopifyEntry {
	name: string;
	summary: string;
	deprecated: boolean;
}

const projectRoot = resolve(import.meta.dirname, "..");
const docsDataPath = resolve(projectRoot, "vendor/theme-liquid-docs/data");

// Tags that are sub-tag syntax, not standalone tags
const EXCLUDED_TAGS = new Set(["else"]);

// --- Main ---

const engine = new Liquid();
const coreFilterNames = new Set(Object.keys(engine.filters));
const coreTagNames = new Set(Object.keys(engine.tags));

const filterShimMap = new Map(
	assayFilterShims.map((filter) => [filter.name, filter]),
);
const tagShimMap = new Map(assayTagShims.map((tag) => [tag.name, tag]));

const filterResult = audit(
	"filter",
	readShopifyData("filters.json"),
	coreFilterNames,
	filterShimMap,
);
const tagResult = audit(
	"tag",
	readShopifyData("tags.json").filter(
		(entry) => !EXCLUDED_TAGS.has(entry.name),
	),
	coreTagNames,
	tagShimMap,
);

writeFileSync(
	resolve(projectRoot, "docs/filters.md"),
	buildMarkdown("Filters", filterResult),
);
writeFileSync(
	resolve(projectRoot, "docs/tags.md"),
	buildMarkdown("Tags", tagResult),
);

console.log(
	`Filters: ${filterResult.counts.parity} parity, ${filterResult.counts.mock} mock, ${filterResult.counts.unsupported} unsupported`,
);
console.log(
	`Tags: ${tagResult.counts.parity} parity, ${tagResult.counts.mock} mock, ${tagResult.counts.unsupported} unsupported`,
);

// --- Core ---

function audit(
	kind: "filter" | "tag",
	shopifyEntries: ShopifyEntry[],
	coreNames: Set<string>,
	shimMap: Map<string, ShimFilter | ShimTag>,
): AuditResult {
	const shimNames = new Set(shimMap.keys());
	const active: AuditedEntry[] = [];
	const deprecated: AuditedEntry[] = [];

	for (const entry of shopifyEntries) {
		const audited = auditEntry(kind, entry, coreNames, shimNames, shimMap);
		if (entry.deprecated) {
			deprecated.push(audited);
		} else {
			active.push(audited);
		}
	}

	// Add Assay shims not in the Shopify list
	const knownNames = new Set(shopifyEntries.map((entry) => entry.name));
	for (const [name, shim] of shimMap) {
		if (!knownNames.has(name)) {
			active.push({
				name,
				kind,
				status: "assay",
				shimStatus: shim.status,
				description: shim.description ?? "",
				hasShopifyDocs: false,
			});
		}
	}

	active.sort((first, second) => first.name.localeCompare(second.name));
	deprecated.sort((first, second) => first.name.localeCompare(second.name));

	const counts = { parity: 0, mock: 0, unsupported: 0 };
	for (const entry of active) {
		if (entry.status === "missing") {
			counts.unsupported++;
		} else if (entry.status === "core" || entry.shimStatus === "parity") {
			counts.parity++;
		} else {
			counts.mock++;
		}
	}

	return { active, deprecated, counts };
}

function buildMarkdown(title: string, result: AuditResult): string {
	const singularTitle = title.slice(0, -1);
	const headers = [singularTitle, "Status", "", "Description"];
	const total = result.active.length;

	const lines = [
		"<!--Auto-generated by `npm run docs:audit`. Do not edit manually.-->",
		"",
		`# ${title}`,
		"",
		`- ✅ Parity: ${result.counts.parity}`,
		`- ☑️ Mock: ${result.counts.mock}`,
		`- Unsupported: ${result.counts.unsupported}`,
		`- **Total:** ${total}`,
		"",
		...formatTable(headers, result.active.map(entryToRow)),
	];

	if (result.deprecated.length > 0) {
		lines.push(
			"",
			"## Deprecated",
			"",
			...formatTable(headers, result.deprecated.map(entryToRow)),
		);
	}

	lines.push("");
	return lines.join("\n");
}

// --- Helpers ---

function readShopifyData(filename: string): ShopifyEntry[] {
	return JSON.parse(readFileSync(resolve(docsDataPath, filename), "utf-8"));
}

function auditEntry(
	kind: "filter" | "tag",
	entry: ShopifyEntry,
	coreNames: Set<string>,
	shimNames: Set<string>,
	shimMap: Map<string, ShimFilter | ShimTag>,
): AuditedEntry {
	const status = coreNames.has(entry.name)
		? "core"
		: shimNames.has(entry.name)
			? "assay"
			: "missing";

	const shim = shimMap.get(entry.name);
	const description = resolveDescription(entry, shim);

	return {
		name: entry.name,
		kind,
		status,
		shimStatus: shim?.status,
		description,
		hasShopifyDocs: true,
	};
}

function resolveDescription(
	entry: ShopifyEntry,
	shim: ShimFilter | ShimTag | undefined,
): string {
	if (shim?.description && entry.summary) {
		console.warn(
			`⚠️  Both shim and Shopify define description for: ${entry.name}`,
		);
	}
	if (shim?.description) return shim.description;
	if (entry.summary) return entry.summary;
	console.warn(`⚠️  No description for: ${entry.name}`);
	return "";
}

function entryToRow(entry: AuditedEntry): string[] {
	const { icon, label } = getStatusWithLabel(
		entry.name,
		entry.kind === "filter" ? coreFilterNames : coreTagNames,
		entry.kind === "filter" ? filterShimMap : tagShimMap,
	);

	const description = entry.description
		.replace(/\|/g, "\\|")
		.replace(/\n/g, " ");

	const docsUrl = `https://shopify.dev/docs/api/liquid/${entry.kind}s/${entry.name}`;
	const link = entry.hasShopifyDocs ? `[🔗](${docsUrl})` : "";

	return [`\`${entry.name}\``, `${icon} ${label}`, link, description];
}
