/**
 * Scans the per-shim files under src/shims/{filters,tags} and writes the
 * barrel (index.ts) for each, importing every shim and exposing
 * registerDefaultFilters / registerDefaultTags.
 *
 * Each shim file's default export is a ShimFilter or ShimTag; the barrel
 * registers each one's `implementation` against the engine under its `name`.
 */

import { readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const projectRoot = resolve(import.meta.dirname, "..");

generateBarrel({
	kind: "filters",
	arrayName: "filters",
	registerCall: "registerFilter",
	registerFnName: "registerDefaultFilters",
});

generateBarrel({
	kind: "tags",
	arrayName: "tags",
	registerCall: "registerTag",
	registerFnName: "registerDefaultTags",
});

interface BarrelSpec {
	kind: "filters" | "tags";
	arrayName: string;
	registerCall: "registerFilter" | "registerTag";
	registerFnName: string;
}

function generateBarrel(spec: BarrelSpec): void {
	const dir = resolve(projectRoot, `src/shims/${spec.kind}`);
	const shimNames = listShimFiles(dir);

	const imports = shimNames
		.map((name) => `import ${toIdentifier(name)} from "./${name}";`)
		.join("\n");
	const arrayMembers = shimNames
		.map((name) => `\t${toIdentifier(name)},`)
		.join("\n");

	const output = `// AUTO-GENERATED by scripts/generate-shim-barrels.ts — do not edit.
import type { Liquid } from "liquidjs";

${imports}

export const ${spec.arrayName} = [
${arrayMembers}
];

export function ${spec.registerFnName}(engine: Liquid): void {
\t${spec.arrayName}.forEach((shim) =>
\t\tengine.${spec.registerCall}(shim.name, shim.implementation),
\t);
}
`;

	const outputPath = resolve(dir, "index.ts");
	writeFileSync(outputPath, output);
	console.log(`Written to ${outputPath}`);
}

function listShimFiles(dir: string): string[] {
	return readdirSync(dir, { withFileTypes: true })
		.filter(
			(entry) =>
				entry.isFile() &&
				entry.name.endsWith(".ts") &&
				!entry.name.endsWith(".test.ts") &&
				entry.name !== "index.ts",
		)
		.map((entry) => entry.name.replace(/\.ts$/, ""))
		.sort();
}

function toIdentifier(fileName: string): string {
	return fileName.replace(/[^A-Za-z0-9_$]/g, "_");
}
