/**
 * Extracts canonical Shopify Liquid names from theme-liquid-docs and writes
 * a minimal TypeScript file with just the name arrays.
 *
 * This keeps the CLI bundle small (~4KB vs ~940KB of full JSON).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface NamedEntry {
	name: string;
}

const projectRoot = resolve(import.meta.dirname, "..");
const docsDataPath = resolve(projectRoot, "vendor/theme-liquid-docs/data");

function readNames(filename: string): string[] {
	const data: NamedEntry[] = JSON.parse(
		readFileSync(resolve(docsDataPath, filename), "utf-8"),
	);
	return data.map((entry) => entry.name);
}

const filterNames = readNames("filters.json");
const tagNames = readNames("tags.json");
const objectNames = readNames("objects.json");

const output = `/**
 * Canonical Shopify Liquid names from theme-liquid-docs.
 * Auto-generated by scripts/generate-shopify-names.ts — do not edit.
 */

export const filterNames = ${JSON.stringify(filterNames)};
export const tagNames = ${JSON.stringify(tagNames)};
export const objectNames = ${JSON.stringify(objectNames)};
`;

const outputPath = resolve(projectRoot, "src/cli/shopify-names.ts");
writeFileSync(outputPath, output);
console.log(`Written to ${outputPath}`);
